- hosts: remoto
  gather_facts: False
  vars:
    pacotes:
      - sysstat
      - docker
      - nginx


  tasks:
  - name: Exibindo variaveis
    user:
      name: "{{ item.name }}"
      shell: "{{ item.shell }}"
      groups: "{{ item.groups }}"
      uid: "{{ item.uid }}"
    loop:
      - name: Aluno1
        uid: 1020
        groups: vagrant
        shell: /bin/bash
      - name: Aluno2
        uid: 1030
        groups: vagrant
        shell: /bin/sh
      - name: Aluno3
        uid: 1040
        groups: vagrant
        shell: /bin/bash